using inventory_dashboard.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace inventory_dashboard.Services;

public class PdfService
{
    public PdfService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateOrderInvoice(Order order)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text("INVOICE")
                    .SemiBold()
                    .FontSize(24)
                    .FontColor(Colors.Blue.Darken2);

                page.Content()
                    .PaddingVertical(1, Unit.Centimetre)
                    .Column(column =>
                    {
                        column.Item().Text($"Order #: {order.Id}");
                        column.Item().Text($"Date: {order.OrderDate:yyyy-MM-dd HH:mm}");
                        column.Item().Text($"Status: {order.Status}");
                        column.Item().Text($"Customer ID: {order.CustomerId}");

                        column.Item().PaddingTop(1, Unit.Centimetre);
                        column.Item().Table(table =>
                        {
                            table.ColumnsDefinition(columns =>
                            {
                                columns.RelativeColumn(3);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(1);
                                columns.RelativeColumn(1);
                            });

                            table.Header(header =>
                            {
                                header.Cell().Text("Product");
                                header.Cell().Text("Qty");
                                header.Cell().Text("Price");
                                header.Cell().Text("Total");
                            });

                            foreach (var item in order.OrderItems)
                            {
                                table.Cell().Text(item.Product?.Name ?? "Unknown");
                                table.Cell().Text(item.Quantity.ToString());
                                table.Cell().Text($"R{item.Price:F2}");
                                table.Cell().Text($"R{(item.Price * item.Quantity):F2}");
                            }

                            table.Footer(footer =>
                            {
                                footer.Cell().ColumnSpan(3).AlignRight().Text("Grand Total:");
                                footer.Cell().Text($"R{order.TotalAmount:F2}");
                            });
                        });
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Inventory Dashboard");
                        x.Span("  |  ");
                        x.Span(DateTime.Now.ToString("yyyy-MM-dd HH:mm"));
                    });
            });
        });

        return document.GeneratePdf();
    }
}
